feat: intro
Ningbo-Mentor-Scheme/book-2020 pull request #9
Opened 2020-07-20 09:29 UTC by imaginebreake

2020-07-21 00:58 UTC, liqing-yang requested changes
叫我 review 就是会事儿很多

2020-07-21 00:58 UTC, xiuxiu0907 commented on README.md
> +虽然很老套，但是不得不说，2020是特别的一年。其中，有四个特别的星期六，分别是：4月4，6月6，8月8，10月10，12月12；同时还有两个闰年，分别是阳历的闰年和阴历的闰年(笑)。言归正传，在这样一个特别的背景下，我们学长学姐们也是希望你们可以在来英国的旅途上少一点麻烦，多一点安心。因此我们决定为你们写一本 handbook，希望能为你们去英国以及落地之后的学习生活带来帮助。
不是五个特别的星期六吗🤔

2020-07-21 00:58 UTC, xiuxiu0907 commented on README.md
> +各位刚刚完成在 UNNC 两年学习生涯，即将在 UNUK 开启人生新篇章的各位，大家好！
_刚刚完成在 UNNC 的两年学业，并即将在 UNUK 开启人生新篇章的各位，大家好！_

修改语病：「各位」的重复使用 and 没有「完成...生涯」这个句式。

2020-07-21 00:58 UTC, xiuxiu0907 commented on README.md
> +虽然很老套，但是不得不说，2020是特别的一年。其中，有四个特别的星期六，分别是：4月4，6月6，8月8，10月10，12月12；同时还有两个闰年，分别是阳历的闰年和阴历的闰年(笑)。言归正传，在这样一个特别的背景下，我们学长学姐们也是希望你们可以在来英国的旅途上少一点麻烦，多一点安心。因此我们决定为你们写一本 handbook，希望能为你们去英国以及落地之后的学习生活带来帮助。
根据[中文文案排版指北](https://github.com/sparanoid/chinese-copywriting-guidelines)，建议中文与数字之间添加空格。

2020-07-21 00:58 UTC, xiuxiu0907 commented on README.md
> +虽然很老套，但是不得不说，2020是特别的一年。其中，有四个特别的星期六，分别是：4月4，6月6，8月8，10月10，12月12；同时还有两个闰年，分别是阳历的闰年和阴历的闰年(笑)。言归正传，在这样一个特别的背景下，我们学长学姐们也是希望你们可以在来英国的旅途上少一点麻烦，多一点安心。因此我们决定为你们写一本 handbook，希望能为你们去英国以及落地之后的学习生活带来帮助。
希望能为你们_去英国以及落地之后的学习生活_带来帮助。

这里「去英国」要不要换一个短语？原来文本中的「落地之后的...」在语义上感觉是包含在「去英国」里的。

2020-07-23 02:53 UTC, liqing-yang requested changes

2020-07-23 02:53 UTC, xiuxiu0907 commented on README.md
> +刚刚完成在 UNNC 两年学习，即将在 UNUK 开启人生新篇章的各位，大家好！
你直接把我的那句话 copy 上来不就好了吗！！我每个字都想过的！！

2020-07-23 02:53 UTC, xiuxiu0907 commented on README.md
> +
不要分段了吧（（（（（？这个只是建议

2020-07-23 02:53 UTC, xiuxiu0907 commented on README.md
> +这本 handbook 主要还是以电子书的形式呈现给大家。其中，源代码的开发工作主要基于 [GitHub](https://github.com/Ningbo-Mentor-Scheme/book-2020/)。源代码会实施部署为静态网页文件，可以[点此](https://ningbo-mentor-scheme.github.io/book-2020/Chap01-Entry/registra
_进行访问，并对中国互联网做了特别的优化,可以_

不要中英文标点混用。

2020-07-23 02:53 UTC, xiuxiu0907 commented on README.md
> +这本 handbook 主要还是以电子书的形式呈现给大家。其中，源代码的开发工作主要基于 [GitHub](https://github.com/Ningbo-Mentor-Scheme/book-2020/)。源代码会实施部署为静态网页文件，可以[点此](https://ningbo-mentor-scheme.github.io/book-2020/Chap01-Entry/registra
_进行访问，并对中国互联网做了特别的优化,可以_

不要中英文标点混用。

2020-07-23 02:53 UTC, xiuxiu0907 commented on README.md
> +
_2020是特别的一年_

2020 后面要不要加个空格（也只是建议

2020-07-23 03:17 UTC, liqing-yang approved these changes

2020-07-23 03:17 UTC, merged